#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
~/.config/polybar/launch.sh

bspc monitor eDP1 -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio              	0.50
bspc config borderless_monocle       	true
bspc config gapless_monocle          	true
bspc config focus_follows_pointer    	true
bspc config top_padding              	21

bspc config active_border_color		"#285577"
bspc config focused_border_color	"#285577"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Gimp state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

